---
language: node_js
node_js:
  - 11

before_install:
  - sudo apt-get -y install imagemagick lftp
  - npm install html-minifier clean-css clean-css-cli

script:
  - scripts/build.sh

deploy:
  - provider: script
    script: bash scripts/push.sh
    skip_cleanup: true
    on:
      branch: master
